name: app
description: SaluMeD mobile application
publish_to: 'none'
version: 2.0.2+47

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: any
  provider: any
  progress_indicators: any
  simple_animations: any
  font_awesome_flutter: 11.0.0
  flutter_login_facebook: any
  socket_io_client: any
  http: any
  intl: any
  dio: any
  snack: any
  flutter_datetime_picker: any
  photo_view: any
  image_picker: any
  carousel_slider: any
  shimmer_animation: any
  google_maps_flutter: any
  sliding_up_panel: any
  flutter_phone_direct_caller: any
  in_app_review: any
  url_launcher: any
  universal_io: any
  onesignal_flutter: any
  assets_audio_player: ^3.1.1
  url_strategy: any
  dropdown_search: any
  country_code_picker: any
  syncfusion_flutter_charts: any
  responsive_grid: any
  uuid: ^4.5.1
  timelines: any
  latlong2: ^0.10.1
  geolocator: any
  firebase_core: any
  firebase_messaging: any
  editable: any
  back_button_interceptor: any
  file_picker: 10.3.10
  syncfusion_flutter_pdfviewer: ^33.2.10
  modal_bottom_sheet: any
  permission_handler: any
  audioplayers: any
  video_player: any
  showcaseview: any
  just_audio: any
  audio_service: any
  hive: any
  hive_flutter: any
  path_provider: any
  fl_chart: any
  app_links: ^7.2.1
  flutter_custom_tabs: any
  webview_flutter: any

dependency_overrides:
  assets_audio_player:
    path: plugins/assets_audio_player
  flutter_datetime_picker:
    path: plugins/flutter_datetime_picker
  timelines:
    path: plugins/timelines
  assets_audio_player_web:
    path: plugins/assets_audio_player_web
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path_ios: assets/images/app_icons/icon_main.png
  image_path_android: assets/images/app_icons/icon_main.png
  adaptive_icon_background: assets/images/app_icons/icon_background.png
  adaptive_icon_foreground: assets/images/app_icons/icon_foreground.png
  android: true
  ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/app_icons/
    - assets/images/medals/
    - assets/images/categories/
    - assets/sound/
    - assets/json/
    - assets/video/
    - assets/mp_form.html

